server:
  port: 8763
  max-http-header-size: 102400
  servlet:
    context-path: /exam_du
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.105.42.45:8761/eureka/
spring:
  application:
    name: client
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  
logging:
  level:
    com.des.client.mapper: debug
    org.aspectj: info